version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
    overwrite: true

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 2000
      runas: ec2-user