services:
  redis:
    container_name: 'imi-redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
  server:
    container_name: 'imi-backend'
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /deploy
    ports:
      - "8080:8080"