name: deploy
on:
  push:
    branches:
      - master
      - release/*
jobs:
  deploy:
    environment:
      name: Deploy Environment
    #    if: github.event.pull_request.merged == true
    env:
      ENV_PATH: ./src/main/resources/.env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: create .env
        run: |
          touch ${{ env.ENV_PATH }}
          echo "${{ secrets.ENV_FILE }}" > ${{ env.ENV_PATH }}
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup Gradle's permission
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://${{ secrets.AWS_BUCKET_NAME }}/deploy/$GITHUB_SHA.zip
      - name: Deploy to EC2 with CodeDeploy
        run: aws deploy create-deployment
          --application-name imi-codedeploy
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name imi-backend
          --s3-location bucket=${{ secrets.AWS_BUCKET_NAME }},bundleType=zip,key=deploy/$GITHUB_SHA.zip